### ISSUE TITLE
distribute InstPackages*.sh in the GAP tarball

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap-distribution#17]
Having to download this script and change its permissions is a unnecessary chore. Why not just package them in the tarball?

**Comment by alex-konovalov** [comment]
Since it now lives in this repository (see e.g. https://github.com/gap-system/gap-distribution/tree/master/testing/stable for stable branch), that may be done easier than before.

An alternative could be to improve further two PRs by @ChrisJefferson and @markuspf (see https://github.com/gap-system/gap/pull/336 and https://github.com/gap-system/gap/pull/387) and get rid of `InstPackages` completely. In the current form, they try to build each package having `Makefile` even if the package has no binaries and used make e.g. to build manuals and/or wrap archives. I think for that purpose there should be a list of packages not compatible with the new package building interface, so one would not try to call `make` in their directories.

**Comment by fingolfin** [comment]
See also https://github.com/gap-system/gap/pull/740

**Comment by alex-konovalov** [comment]
This is closed - the need will be addressed by #19 in the next minor release.
