### ISSUE TITLE
Replace `git clone --depth 1 -b` by `git archive`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-distribution#27]
Instead of making a shallow clone and then deleting its `.git` dir, I recommend using `git archive` instead.
That is also what I use in https://github.com/fingolfin/ReleaseTools

**Comment by alex-konovalov** [comment]
I would like however to make a clone in order to have in the log file details about the revision from which the GAP distribution has been prepared. I am afraid I will not have this using `git archive`.

**Comment by alex-konovalov** [comment]
Doing this carefully would require to get a commit hash for the tip of the repository, and then using `git archive` to get exactly that state. Otherwise it could happen that someone will make a commit exactly between those events, and this will result the hash does not matching the state of the repository archive.

I will keep this open, but consider this a low priority for me.

**Comment by fingolfin** [comment]
Thinking about this again, there isn't really a strong reason to do this.
