### ISSUE TITLE
Remove HAPprime from the distribution

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-distribution#43]
Graham Ellis wrote: "Some years back I extracted, corrected and stored in ~/pkg/Hap1.11/lib/HapPrime that portion of HAPprime that is used in HAP. So HAP never calls the HAPprime package and I would guess that no user ever calls HAPprime.  [...] Is it possible to just drop HAPprime from the distribution?"

**Comment by slel** [comment]
2021-01 request of a user trying to use a HAPprime function via Sage on CoCalc:

- [Ask Sage question 55375: Mysterious "must have a value" error](https://ask.sagemath.org/question/55375)

**Comment by fingolfin** [comment]
They can still download it, but it is unmaintained and not shipped with GAP anymore.

**Comment by slel** [comment]
Yes, that's what I answered there. I also opened https://github.com/gap-system/GapWWW/issues/214 to fix some links.

**Comment by slel** [comment]
Two more questions (sorry if this is not the best place for this discussion).

a.

Would it be possible to unarchive [the HAPprime repository](https://github.com/gap-packages/happrime)
and update its `PackageInfo.g` and `README.md` so they state

- HAPprime is no longer maintained, and no longer shipped with GAP since GAP 4.9
- some of the functionality is now in HAP
- to use functionality that is not in HAP, one can still install it

Then archive it again. See https://github.com/gap-system/GapWWW/pull/215#issuecomment-764951232

b.

In GAP 4.11, installing HAPprime with `PackageManager` fails,
is that expected?

**Comment by alex-konovalov** [comment]
@slel 

yes for (a) - preferably not for a long time, just unarchive, make changes, archive back

yes for (b) - the "package list" means the list of packages from GAP distro. Other packages can be added but need to be specified differently. @mtorpey can tall more.

**Comment by mtorpey** [comment]
(b) Indeed, packages installed by name are taken straight from [this list in gap-distribution](https://raw.githubusercontent.com/gap-system/gap-distribution/master/DistributionUpdate/PackageUpdate/currentPackageInfoURLList), and it looks like GAPprime isn't there right now.

You can still install it by specifying an archive URL.  Something like this:
```
InstallPackage("https://github.com/gap-packages/happrime/releases/download/v0.6dev/happrime-0.6dev.tar.gz");
```
or even using a git link:
```
InstallPackage("https://github.com/gap-packages/happrime.git");
```
Although I haven't tried either of these. :)
