### ISSUE TITLE
cleaning up package sources for distribution

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap-distribution#7]
a typical release of packages has a lot of needless stuff that just takes up space,
such as docs as pdf/dvi (and TeX work files), generated xml...

e.g. there are 108 log files

gap4r8/pkg]$ find . -name *.log | wc -l
108

similarly:
gap4r8/pkg]$ find . -name *.dvi | wc -l
32
gap4r8/pkg]$ find . -name *.pdf | wc -l
244

there are 11 copies of convert.pl script (why are they there at all? isn't it a part of GAP proper?)

there is even an .exe file in
grape/bin/i686-pc-cygwin-gcc-default32/dreadnautB.exe
(and we talk about SOURCE, for Pete's sake)

Before a package can make it into Sagemath packages, all this has to cleaned.
Is it possible to produce a source release tarball with "make distclean" ran on
each pkg ?

**Comment by alex-konovalov** [comment]
Our long-term policy is to redistribute packages as is. In particular, a package archives should include prebuilt documentation to be usable immediately, and there should be no difference in the package archives whether they may be downloaded from the GAP website or from the package's website. Moreover, we do not ask package authors to provide an extra archive with the source distribution of the package with nothing built.

It may be useful if we could rebuild package manuals because sometimes package authors are not building them in the right place and cross-references are not right (I have a test that uses `linklint` to detect such cases). But the problem is that there is no standardised way to build GAPDoc-based package manuals - packages use similar but slightly different scripts, and furthermore there are packages that still use the old `gapmacro.tex`-based format. 

Hence we have what you're reporting here. Furthermore:
* We can not say whether pdf is a package manual or another file (e.g. preprint) that the author put there. 
* If this is a .tex file for a gapmacro.tex based manual, it is actually needed for the help system, so it should be in the package. 
* As for `convert.pl` script, it is used to create HTML version of the manual for `gapmacro.tex`-based manuals.

Regarding GRAPE, Leonard told that this will be gone in the new version of GRAPE.

**Comment by dimpase** [comment]
There is nothing wrong with sensible changes in policies. E.g. asking authors to provide build-able docs rather than pre-built docs makes perfect sense.

**Comment by fingolfin** [comment]
While I also wouldn't mind if these files were cleared away, getting all package authors to do that is not quite trivial.

And once again I have to wonder: Do you have actual reasons for this besides purely aesthetical ones? You say you "have to" remove them, but why? What is the harm in a tiny log file sitting around?

**Comment by dimpase** [comment]
It is unacceptable from Sage coding standards point of view to have crap packaged, that's why. 
We have scripts that clean things up, but they are not perfect, often hand intervention is needed.
Thus GAP outsources  this cleaning job over...

**Comment by frankluebeck** [comment]
The content of the package directories is the responsibility of the package authors. 

A few .log or .aux files are small compared to the rest and so are not really disturbing.

.pdf and .dvi files are obviously not *needless stuff* (although I suggest since many years to include pdf instead of dvi). These files can be used by the GAP help system, and they are obviously useful for printing a manual.

Having a local copy of the no longer maintained `convert.pl` sounds reasonable to me.

An .exe file in a package directory is probably a (minor) bug which should be reported to the package author. 

We ask authors to provide pre-built documentation such that the provided archives can be **redistributed** without change.

"Sage coding standards" are not relevant for GAP package authors.

**Comment by dimpase** [comment]
it is mere question of time for these dvi and pdfs starting to contain
photos of favourite dogs of package authors, or worse. Pdfs can contain
viruses, this is well-known.

In a sane world pdfs and like (unless they are figures to be included in
the docs) do not belong to source distributions, full stop.

**Comment by bh11** [comment]
@dimpase As @alex-konovalov and @frankluebeck wrote, GAP packages aren't source distributions (and neither is GAP itself), as they are supposed to contain the pre-built documentation. 

In this way, packages not containing binary code do not need to be installed. 

I don't think that pdf files pose a higher security risk than allowing programs to be generated on your computer from source. Beware of c code producing cat images ;-)

If sage really requires a different format, it's probably best to approach package authors directly.

**Comment by dimpase** [comment]
Sage needs binary stuff (and needless stuff, e.g. .aux files) stripped. I have been packaging GAP packages for Sagemath for the past 6 years or so, and it's tiring to no end to have to do this half-manually time and time again. Particularly as upstream does not care, it seems.

Besides, yes, there are pdf-based viruses out there, it is absolutely not a joking matter.
Suppose a package author built a distribution on an infected computer.

It is true also that one can also sneak a backdoor or something like this into source C/C++ code , but this is harder to do. At least it could not happen by itself, for this the author must be acting with malice or be very careless with access to the package source.

**Comment by alex-konovalov** [comment]
I will close this issue - we redistribute packages "as is", so the content of the package directories is exactly as provided to package authors. If you would like to reach package authors and give some advice, the best ways to do this are:
* write to the open GAP development mailing list
* submit issues and PRs: http://gap-packages.github.io/ is here to help to find packages
* participate in writing this guidance for package authors: https://github.com/gap-system/gap/pull/484

**Comment by dimpase** [comment]
It's not about more advice or better guidelines,it's about better rules, needed to make distributing GAP packages in Sage easier.

**Comment by fingolfin** [comment]
@dimpase Of course it would be possible to change something in this regard, as was discussed here. The point is: We (the GAP group) see no immediate reason to do so; we have nothing to gain from it, and are in general understaffed; so we choose to spend our precious little resources on other concerns that are more pressing for us. And we even disagree with some points (e.g. for us it is an important features that the PDF is shipped with the packages).

That said, I also don't like the .aux, .log etc. files being included (that's why my ReleaseTools strip them). But this is mostly out of a sense for cleanlieness, not for any good technical reasons I can think of.

In the end, making it easier to distribute GAP in Sage is something where I'd argue Sage has a much, much higher interest in than GAP. So, I'd welcome active contirbutions. E.g. contacting package authors whose packages include undesirable files (such as precompiled executables) and convince them to change this. I have spent considerabl hours of work doing similar things, and I think Alex had spent a magnitude more on chasing package authors. If you want to help with that, that's most welcome.

But I don't see what "rules" we should make on that -- any such rules need a good justification before we impose them on package authors; and so far, all I heared "pdfs could contain viruses" which of course is possible, but not something I am actually concerned about; and "sage needs this", which is not really convincin, either .

**Comment by dimpase** [comment]
Regarding GAP being undestaffed - I can only point out that improving GAP/Sage interoperability (packaging including) is a task of the EU grant more than one person at St.Andrews is being paid from. Not that there are lots of details on it in the grant proposal, but still:
https://github.com/OpenDreamKit/OpenDreamKit/issues/51

Surely, chasing package authors can be done. I have just spent perhaps a week or more of my time convincing the author of a very well-respected software package to change the licence in a way that would make it possible for Sage to distribute it; that included a threat to fork the package, and even actually creating a repo with a fork. This did work in the end. I (and several other Sage devs) have also recently spent several days trying to convince the author of another well-respected software package to please accept my patches to make the package buildable in a sane way - unsuccessfully, we now are maintaining a fork. I am not going to do this very often, and certainly not on the scale needed for GAP packages at the moment.

It is in fact quicker to create a fork than to convince people. If GAP was willing to change packaging rules to make convincing  unnecessary, it would a be a very welcome change.

Otherwise it seems that the only way forward to bring more GAP packages into Sage it to increase the size of our mini-fork, called gap-packages package. 
http://www.mirrorservice.org/sites/www.sagemath.org/spkg/upstream/gap_packages/index.html
However, this is not what I'd call improving interoperability of Sage and GAP, this would rather would be a one-sided effort, hard to keep up to date, and potentially leading to more people using outdated versions, more fragmentation etc etc.

**Comment by frankluebeck** [comment]
I would like to add one more aspect to this discussion:

GAP and GAP packages are partly written by mathematicians who obviously are able to write some useful code but who often are not software developers with detailed knowledge about Makefiles, wrapping processes, conventions in (other) software projects, and so on. 

Therefore the general policy for GAP packages was always to impose as few formal rules/conditions on package authors as possible; just enough that using the package is made very easy for end users  (installation in most cases means just downloading an unpacking). 

I can think of a few additional rules we may want to introduce (for example to achieve a unification of the build processes for packages that need compilation for their full functionality). But I do not agree that any of the rules suggested by @dimpase would lead to any benefit for GAP and its users.

**Comment by dimpase** [comment]
@frankluebeck : surely GAP users who get to inspect GAP source code will benefit from seeing clean directory structures, no leftover files, etc etc. Or do you rather prefer to work at a littered desk than at  clean desk?

**Comment by dimpase** [comment]
I think uncluttered directories are very important (in particular to newcomers who have little clue about directory structures of GAP). Saying that cleaning them up is not beneficial to GAP users is a lie.

**Comment by alex-konovalov** [comment]
FYI, The manual of the GAP package Example has the section [Structure of a GAP Package](http://www.gap-system.org/Manuals/pkg/example/doc/chapA.html#X8383876782480702) which explains the meaning of various standard files and directories. Most, if not all, files in the initial issue (log, dvi, pdf, convert.pl) are located in the `doc` directory, which in most cases should be used via the help system rather than by looking there. They are never located in the package root directory, and the name `doc` clearly speaks for itself. Therefore, I don't see any problem for a newcomer.
