### ISSUE TITLE
remove READMEs from top level of pkg/

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap-distribution#9]
What are these README.blah doing there? By right, 

     mv README.blah blah/README 

will clean a lot up...

**Comment by alex-konovalov** [comment]
Some packages have `blah/README`, some `blah/REAME.md` or `blah/README.txt` etc. `PackageInfo.g` file specifies which file to use for `pkg/README.blah` and also for the package overview page on the website.

While having README on the website is definitely useful, I am indeed not so sure why a copy of it should be in `pkg` if there is one sitting just one directory down. Maybe one of the reasons was that the path to `pkg/README.pkgname` name is stable whatever the name of the directory with the package will be? I don't remember, as this was in use for quite a long time. I would be happy to get rid of `pkg/README.ppkgname` files, if others support this.

**Comment by fingolfin** [comment]
I also see no reason to keep these around. But perhaps ask on the GAP mailing list if somebody remembers (perhaps point them to this issue and encourag them to comment here)

**Comment by frankluebeck** [comment]
When there were fewer packages we probably found it convenient to have the README files of all packages available with uniform names in one directory.

But I guess that by now these are rarely, if ever, used.

I suggest to comment out the code that copies these files during the wrapping process for the next release. If nobody complains, this code can be deleted.

**Comment by alex-konovalov** [comment]
@frankluebeck thanks - assigned to myself and will do this.

**Comment by fingolfin** [comment]
Note that the README.pkgname files are downloaded from the package's README_URL (the code stresses that), and thus it might in theory differ from that inside the package itself. Of course one might consider that a bad idea... ;-).

Which makes me wonder: If we drop this, is there any reason to keep `README_URL` as a required field for `PackageInfo.g` ?

**Comment by fingolfin** [comment]
@frankluebeck Any particular reason you want the code commented out, instead of being removed? I normally strongly advice against that, as commented out tends to quickly rot, and one of the main purposes of a version control system is to allow you to quickly recover deleted code if you want it. I.e. if we have a simple commit which removes that code, it's a one line git command to return it later on...

That said, it won't hurt in this case, it just feels wrong.

**Comment by frankluebeck** [comment]
@fingolfin asks:
> Which makes me wonder: If we drop this, is there any reason to keep README_URL as a required field for PackageInfo.g ?

There are links to (copies of) these files on the package pages of the GAP website. I would say that this is reasonable. (Maybe check how these files are copied to the website - in particular that they are not copied from a distribution archive.)

> @frankluebeck Any particular reason you want the code commented out, instead of being removed?

Of course, proceed as you like. (When I'm not 100% sure about all implications of removing some code, I do it as I suggested above: first uncomment it, and if after a while no problems occured, delete it completely in a second step. Just because it is much easier to uncomment the code if needed instead of fiddling with version control.)

**Comment by alex-konovalov** [comment]
As @fingolfin says, the comment in [PackageUpdate/PackageInfoTools.g](https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/PackageInfoTools.g) says that these files are copied from package homepage (not from the archive!), so in theory they may differ (what would be not a good idea). The GAP website contains links to exactly that files (and not from the package archive).

**Comment by fingolfin** [comment]
@alex-konovalov Yes, they may differ, but I'd argue that's a bug. So, I still think we should drop them -- and eventyally also `README_URL` -- at least I never had any reason to use these. If I want to learn about a package before downloading it, I look at its homepage; I don't try to download a README from its homepage.

**Comment by dimpase** [comment]
Two sets of READMEs, potentially contradicting each other, that's certainly a great feature, a true killer feature... I suggest they they should also point out to each other, to increase the user satisfaction, and please package authors...

**Comment by alex-konovalov** [comment]
@fingolfin: my current plan is  to remove `pkg/README.pkgnames` from GAP 4.8.3 distribution. Indeed I never used them at all - I always change to the very package directory to see the README file there. 

As for the files fetched from README_URL and available on GAP website, I suggest to leave them at least for now. In a hypothetical scenario, a user may be interested in the README only, the package archive may be large, and the original website may be non-available.

BTW, just this morning I've reported that README_URL is not accessible for one of the packages...

**Comment by alex-konovalov** [comment]
The original issue (remove READMEs from top level of pkg/) resolved in https://github.com/gap-system/gap-distribution/commit/b87dd8086be86f0bf635d92e2dbc5f967bc78ffa

**Comment by frankluebeck** [comment]
When the READMEs were introduced most packages probably had no website (we just copied the archive and the README to some ftp-server). The idea was that the README contains some basic information about the content of the package, as well as installation instructions. How many of the distributed packages have a website now? If this is true for essentially all of them  I agree that the old READMEs are no longer needed (or at least can be made optional).

**Comment by alex-konovalov** [comment]
@frankluebeck could you please explain in more details why this issue has been reopened? I have resolved the original issue from the title (remove READMEs from top level of pkg/) in b87dd80 and it's not clear to me if by "the old READMEs are no longer needed" you mean the same action or anything else? If anything else, I think an explicit TODO here or a new follow-up issue may be more useful.

**Comment by frankluebeck** [comment]
@alex-konovalov: sorry, I don't understand your last post. I just added a comment to the recent discussion here (probably mainly on the last post by @fingolfin).

**Comment by alex-konovalov** [comment]
@frankluebeck when you enter a comment on a closed issue, there are two buttons below: grey "reopen and comment" and green "comment". If you press the green one, it leaves a comment without reopening. But perhaps you accidentally pressed the grey one. No problem, then I will just close this issue again (and also #7 which apparently had the same action). It was better just to check with you in case you had some other intention.

**Comment by alex-konovalov** [comment]
@frankluebeck BTW, I can't answer your question "How many of the distributed packages have a website now?" precisely, because many of them have the website specified in PackageInfo.g and their new versions pass validation without a problem. But a more detailed look may reveal that the "website" is just a directory listing where one can see package archives, README and PackageInfo.g. Such packages are clearly benefiting from our overview pages. Another cases are packages where the original website is gone, but because we're still redistributing them, we keep the overview site.
